version: '3.8'

services:
  backend: 
    build: ./server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env 
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "start"]
  
  frontend: 
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "start"]
    